config/routes.rb
Rails.application.routes.draw do
  get 'items/index' 

  get 'items/edit'

  get 'items/show'

  get '/items/', :to => 'items#index', :as => :items

  root 'visits#index'
  get 'visits/:id/new_item_to_visit' => 'visits#new_item_to_visit'
  get 'visits/:id/new_item_visit/' => 'visits#new_item_visit'
  get 'visits/find_car' => 'visits#find_car', as: :find_car
 post 'visits/:id/new_item_visit/' => 'visits#new_item_visit'
 get 'visits/seach_form' => 'visits#seach_form', as: :seach_form

 post 'visits/create_visit_owner' => 'visits#create_visit_owner', as: :create_visit_owner
    delete 'visits/:id/destroy_item_visit/:item_id' => 'visits#destroy_item_visit'

  resources :items

resources :visits do
  resources :owners 
  resources :items
  put :create_item_to_visit, :on => :member
end

patch 'visits/:id/status' => 'visits#status'
  get 'visits/:id/car_visits' => 'visits#car_visits', :as => 'car_visits'

post 'visits/:id/create_item_to_visit' => 'visits#create_item_to_visit'

end

app/models/car.rb
class Car < ActiveRecord::Base
belongs_to :owner
end

app/models/cart.rb
class Cart < ActiveRecord::Base
belongs_to :visit
belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base

has_and_belongs_to_many :visits
end

app/models/items_visit.rb
class ItemsVisit < ActiveRecord::Base
	belongs_to :visit
	belongs_to :item
end

app/models/owner.rb
class Owner < ActiveRecord::Base
	has_many :cars
	has_many :visits
	accepts_nested_attributes_for :visits


end

app/models/visit.rb
class Visit < ActiveRecord::Base
has_and_belongs_to_many :items
#has_many :items, through: :carts
belongs_to :owner

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
  end

  def edit
  end

  def show
  	@items = Item.all
  end

  def new
  	@item = Item.new
  end
  def create

   @newitem = Item.new(item_params)
   @newitem.save  
   @visit = Visit.find(params[:visit_id])
   items = []
   items << @newitem
   @visit.items << items
   @visit.save
    respond_to do |format|
      format.html { redirect_to edit_visit_url(@visit), notice: 'Task was successfully destroyed.' }
      format.json { redirect_to edit_visit_url(@visit), notice: 'Task was successfully destroyed.' }
  end
  end

  def destroy
    @item = Item.find(params[:id])
    @visit = Visit.find(params[:visit_id])
    @item.destroy
        respond_to do |format|
      format.html
      format.json { render 'visits/destroy.js.erb' }
  end
end

  private
  def item_params
  params.require(:item).permit(:title,:description,:price)
  end
end
	

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController


  def new

      @owner = Owner.new
      @visit = @owner.visits.new
      @found_owner = true
  end


  def find_car

    @owner = Owner.find_by(car_number: params[:car_id].to_i)
    if !@owner.nil?
    @visit = @owner.visits.new
    @found_owner = true

    render 'find_car'
  else
    @owner = Owner.new
    @visit = @owner.visits.new
    @found_owner = false
    render 'new'
  end


  end


  def create
  @owner = Owner.new(owner_params)
  @owner.save
  @visit = @owner.visits.new(visit_params)
  @visit.save
  @items = @visit.items
  render '_show'
  end


def create_visit_owner

@owner = Owner.find(params[:id])
@visit = @owner.visits.new(visit_params)
@visit.save
@items = @visit.items
  render '_show'

end

def search_form
end

    def index
  	  @visits = Visit.all
      @owners = Owner.all
    end

    def show
       @visit = Visit.find(params[:id])
       @items = @visit.items
       @owner = @visit.owner
    end

   def edit
    @visit = Visit.find(params[:id])
    @items = @visit.items
    @owner = @visit.owner
    @newitem = Item.new
   end

def destroy_item_visit

    @item = Item.find(params[:item_id])
    @visit = Visit.find(params[:id])
    @items = @visit.items
    @visit.items.destroy(@item)
    @visit.save

  end


def update
  respond_to do |format|

@visit = Visit.find_by(id: params[:id])
@visit.owner.update_attributes(owner_params) 
@visit.update_attributes(visit_params)

@owner = @visit.owner
@items = @visit.items
format.js 
end
end

def car_visits

  @visit = Visit.find_by(id: params[:id])

  @owner = Owner.find_by(car_number: @visit.owner.car_number.to_i) 
  

  @visits = @owner.visits.order(created_at: :desc)
end


def status

@visit = Visit.find(params[:id])

@visit.open = !@visit.open
@visit.save
end


end



def new_item_visit
@visit = Visit.find_by(id: params[:id])
@newitem  = Item.new
end

def create_item_visit
  @newitem = Item.new(item_params)
  @newitem.save  
  @visit = Visit.find(params[:id])
  @visit.items << @newitem
  @visit.save
end





  
    private

def owner_params
  params.require(:owner).permit(:name,:car_number,:car_year,:car_type,:car_model,:car_km,:phone,:email,:car_next_service_date)
end 

private
def visit_params
  params.require(:visit).permit(:notes,:owner_id)
end





  def destroy
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/items/_create.js.erb
$('#table-of-items').html("<%= escape_javascript (render 'show') %>");

app/views/items/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @item, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>

        <div class="form-group">
          <%= f.label :title, class:"control-label" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :price, class: "control-label" %>
          <%= f.text_field :price, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description, class: "control-label" %>
          <%= f.text_field :description, class: "form-control" %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/_new.html.erb
<div class="modal-header">
<h3>New item for visit</h3>
</div>
<%= render "form" %>

app/views/items/_new.js.erb
$("#product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/items/_show.html.erb
   <tbody id="table-of-items">

              <% 
          total = 0
          @items = Item.all
          @items.each do |i| 
          total += i.price.to_i
        %>
      <tr>
        <td><%=i.title%></td>
        <td><%=i.description%></td>
        <td><%=i.price%></td>
      </tr>
<% end %>

      <tr>
             <td></td>
                        <td>סכ"ה</td>

        <td><%=total%></td>

      </tr>
            <tr>
        <%=form_for @newitem, :controller => :visits, :action => :create_item_to_visit, :method => "post", remote: true,:id => @visit.id  do |item|   %>
        <td> <%=item.text_field  :title, :placeholder => @visit.id ,:class => "form-control input-sm" %></td>
        <td> <%=item.text_field  :description, :class => "form-control input-sm" %></td>
        <td> <%=item.text_field :price, :class => "form-control input-sm" %></td>
        <%= hidden_field_tag :visit_id, @visit.id %>
      </tr>
      <tr>
      	<td> <%= item.submit :submit %></td>
      </tr>
      <% end %>
    </tbody>

app/views/items/destroy_item_visit.html.erb
Deleted?

app/views/items/destroy_item_visit.js.erb
$("#table-of-shit").html("<%= j (render 'table_of_shit') %>")

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<div class="modal-header">
<h3>New item for visit</h3>
</div>
<%= render "form" %>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="rtl">
<head>
  <title>Garage</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.0/css/bootstrap-datepicker3.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
<%= javascript_include_tag "http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.6.4.min.js" %>
<%= javascript_include_tag "http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js" %>

  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
           <li role="presentation" class="active"><%=link_to "דף הבית", visits_path, remote: true, class: 'btn btn-primary' %></li>
            <li role="presentation" class="active"><%=link_to "טיפול חדש", new_visit_path, remote: true, class: 'btn btn-primary' %></li>
        	<li role="presentation" class="active"><%=link_to 'דו"חות', new_visit_path, remote: true, class: 'btn btn-primary' %></li>

          </ul>
        </nav>
        <h3 class="text-muted" align="left">שם מוסך</h3>
      </div>
    </div>
    <div id="container_index">
      <%= yield %>
  	</div>

</body>
</html>

app/views/visits/_find_car.html.erb
      
<div class="container" >
  <div class="panel panel-default" >
  	    <div class="panel-heading">

<%= form_tag(find_car_path, remote: true, method: "get") do %>

<%= text_field_tag :car_id %>
<%=	submit_tag "Find", class: "btn btn-primary" %> 

<%end%>
</div>


<%=form_for @owner.visits.new,  url: {  :action => :create_visit_owner, params: { id: @owner.id } } , :html => { :method => "post" } do |f| %>

<%=fields_for @owner do |o| %>


    <div class="panel-body"> פרטי הלקוח והרכב

    	<div class="row">
			<div class="col-xs-4" style='float:right'>
				<%=o.label "שם לקוח" %>
				<%=o.text_field :name, disabled: true, :class => 'form-control'%>
				


			</div>
			<div class="col-xs-4" style='float:right'>

				<%=o.label 'טלפון לקוח' %>
				<%=o.text_field :phone, disabled: true,:class => 'form-control'%>

			</div>

			<div class="col-xs-4" style='float:right'>
				<%=o.label 'דוא"ל' %>
				<%=o.text_field :email, disabled: true, :class => 'form-control'%>
				
  			</div>

       		<div class="col-xs-2" style='float:right'>
  				<%=o.label "סוג רכב" %>
				<%=o.text_field :car_type, disabled: true, :class => 'form-control'%>
			</div>
       		<div class="col-xs-2" style='float:right'>
        
     		   <%=o.label "דגם" %>
      	       <%=o.text_field :car_model, disabled: true,  class: 'form-control'%>
        
   			</div>
			<div class="col-xs-2" style='float:right'>
				<%=o.label 'שנת יצור' %>
				<%=o.text_field :car_year, disabled: true, :class => 'form-control'%>
			</div>
      		<div class="col-xs-2" style='float:right'>
        
  			   <%=o.label 'ק"מ' %>
   			   <%=o.text_field :car_km, disabled: true,  class: 'form-control'%>
        
  			 </div>

				
			<div class="col-xs-4">
				<%=o.label "מס' רכב" %>
				<%=o.text_field :car_number,disabled: true, :class => 'form-control'%>
			</div>






            <div class="col-xs-4" style='float:right'>
        
        		<%=o.label 'הטיפול הבא' %>
       			 <%=o.text_field :car_next_service_date, disabled: true,class: 'form-control'%>
        
       		</div>
			<div class="col-xs-4">
				<br>
				<%=f.submit "הוסף טיפול", :class => "btn btn-primary btn-md btn-block"%>
			</div>
			<div class="col-xs-12">
				<%=f.label "הערות לטיפול" %>
				<%=f.text_area :notes ,disabled: false, :class => 'form-control', :rows => 7%>

			</div>



		</div>
  </div>

</div>
<% end %>
<%end %>

app/views/visits/_form.html.erb
<% @visit = Visit.find_by(id: params[:id])
  @newitem = Item.new
  %>
 <tr>

       <%=form_for @newitem, :controller => :visits, :action => :create_item_visit, :method => "post", remote: true,:id => @visit.id  do |item|   %>
        <td> <%=item.text_field  :title, :placeholder => @visit.id ,:class => "form-control input-sm" %></td>
        <td> <%=item.text_field  :description, :class => "form-control input-sm" %></td>
        <td> <%=item.text_field :price, :class => "form-control input-sm" %></td>
        <%= hidden_field_tag :visit_id, @visit.id %>

      </tr>
      <tr>
        <td> <%= item.submit :submit %></td>
      </tr>
      <%end%>

app/views/visits/_index.html.erb
<table class="table table-hover" style="width: 90%; align: center;    margin-left:auto; margin-right:auto;">
    <thead>
        <tr>
            <th>מס' רכב</th>
            <th>סור רכב</th>
            <th>שנת יצור</th>
            <th>לקוח</th>
            <th>טלפון</th>
            <th>תאריך כניסה</th>
            <th>סטטוס</th>
        </tr>
    </thead>
    <tbody>
        <%  @visits.each do |f|  
                    btn_style = ""
                    if f.open?
                        btn_style = "red"
                        button_text = "פתוח"
                     else
                        btn_style = "blue"
                        button_text = "סגור"
                    end
        %>
        <tr>
        <td><%=link_to f.owner.car_number, visit_path(f),remote: true%></td>
        <td><%= f.owner.car_type  %></td>
        <td><%= f.owner.car_year %></td>
        <td><%= f.owner.name%></td>
        <td><%= f.owner.phone%></td>
        <td><%=f.created_at.strftime("%d/%m/%Y")%></td>
        <td><button type="button" class="w3-btn w3-<%=btn_style%>"><%=button_text%></button></td>
        </tr>
    </tbody>

<div id="product-modal" class="modal fade"></div>
        <%end%>

app/views/visits/_new.html.erb
<div class="container" >
	<div class="panel panel-default">
    	<div class="panel-heading">

<%= form_tag(find_car_path, remote: true, method: "get", :id => 'search_form') do %>

<%= text_field_tag :car_id, '', :placeholder => 'חפש רכב לפי מספר',  :id=> 'car_number'  %>
<%=	submit_tag "Find", class: "btn btn-primary" %> 
<%if !@found_owner %>
<span id="not_found_label" class="label label-danger">לא נמצא רכב מספר <i>  <%=params[:car_id] %> </il> במערכת</span>
<% end %>
<%end%>
		</div>
<%=form_for @visit do |f| %>

<%=fields_for @owner do |o| %>
		<div class="panel-heading">
		<%=submit_tag "הוספת לקוח חדש",:class => "btn btn-primary active",:id=> "clicked_add", :type => 'button'%>
    	
    	</div>

    <div class="panel-body" id="new_owner_div" style="display:none"> פרטי הלקוח והרכב

    	<div class="row">
			<div class="col-xs-4" style='float:right'>
				<%=o.label "שם לקוח" %>
				<%=o.text_field :name, :class => 'form-control'%>



			</div>
			<div class="col-xs-4" style='float:right'>

				<%=o.label 'טלפון לקוח' %>
				<%=o.text_field :phone, :class => 'form-control'%>

			</div>

			<div class="col-xs-4" style='float:right'>
				<%=o.label 'דוא"ל' %>
				<%=o.text_field :email, :class => 'form-control'%>
				
  			</div>

       		<div class="col-xs-2" style='float:right'>
  				<%=o.label "סוג רכב" %>
				<%=o.text_field :car_type, :class => 'form-control'%>
			</div>
       		<div class="col-xs-2" style='float:right'>
        
     		   <%=o.label "דגם" %>
      	       <%=o.text_field :car_model,  class: 'form-control'%>
        
   			</div>
			<div class="col-xs-2" style='float:right'>
				<%=o.label 'שנת יצור' %>
				<%=o.text_field :car_year, :class => 'form-control'%>
			</div>
      		<div class="col-xs-2" style='float:right'>
        
  			   <%=o.label 'ק"מ' %>
   			   <%=o.text_field :car_km,   class: 'form-control'%>
        
  			 </div>

				
			<div class="col-xs-4">
				<%=o.label "מס' רכב" %>
				<%=o.text_field :car_number, :class => 'form-control'%>
			</div>






            <div class="col-xs-4" style='float:right'>
        
        		<%=o.label 'הטיפול הבא' %>
       			 <%=o.text_field :car_next_service_date, class: 'form-control'%>
        
       		</div>
			<div class="col-xs-4">
				<br>
				<%=f.submit "הוסף טיפול", :class => "btn btn-primary btn-md btn-block"%>
			</div>
			<div class="col-xs-12">
				<%=f.label "הערות לטיפול" %>
				<%=f.text_area :notes ,:class => 'form-control', :rows => 7%>

			</div>



		</div>
  </div>

</div>
<% end %>
<%end %>

app/views/visits/_new_item_visit.html.erb
<div class="modal-header">
<h3>New item to visit</h3>
</div>
<%= 
@visit = Visit.find(params[:id])
render "form" %>

app/views/visits/_show.html.erb
<%f = @visit 
  o = @owner
         btn_style = ""
          if !f.open?
               btn_style = "primary"
               button_text = "פתוח"
          else
              btn_style = "danger"
              button_text = "סגור"
          end
%>
<div class="container" id="visit_show">
  <div class="panel panel-default" >
    <div class="panel-heading">טיפול ברכב מספר <%=@owner.car_number%> מיום : <%=@visit.created_at.strftime("%d/%m/%Y")%>
    
    </div>

    <div class="panel-body"> פרטי הלקוח והרכב
      <div class="row">
        <div class="col-xs-4" style='float:right'>
          <%=label_tag "שם לקוח" %>
          <%=text_field_tag :name,o.name, disabled: true, :class => 'form-control'%>
        </div>
        <div class="col-xs-4" style='float:right'>

          <%=label_tag 'טלפון לקוח' %>
          <%=text_field_tag :phone,o.phone, disabled: true, :class => 'form-control'%>
        </div>

        <div class="col-xs-4" style='float:right'>
          <%=label_tag 'דוא"ל' %>
          <%=text_field_tag :email,o.email, disabled: true, :class => 'form-control'%>
        </div>

        <div class="col-xs-2" style='float:right'>
          <%=label_tag "סוג רכב" %>
          <%=text_field_tag :car_type,o.car_type, disabled: true, :class => 'form-control'%>
        </div>
        <div class="col-xs-2" style='float:right'>
          <%=label_tag "דגם" %>
          <%=text_field_tag :car_model, o.car_model, disabled: true, :class => 'form-control'%>
        </div>
        <div class="col-xs-2" style='float:right'>
          <%=label_tag 'שנת יצור' %>
          <%=text_field_tag :car_year, o.car_year, disabled: true, :class => 'form-control'%>
        </div>
        <div class="col-xs-2" style='float:right'>
          <%=label_tag 'ק"מ' %>
          <%=text_field_tag :car_km, o.car_km,  disabled: true, :class => 'form-control'%>
        </div>
        <div class="col-xs-4">
          <%=label_tag "מס' רכב" %>
          <%=text_field_tag :car_number,o.car_number, disabled: true, :class => 'form-control'%>
        </div>
        <div class="col-xs-4" style='float:right'>
          <%=label_tag 'הטיפול הבא' %>
          <%=text_field_tag :car_next_service_date, o.car_next_service_date, disabled: true, :class => 'form-control'%>
        </div>

        <div class="col-xs-4">
          <br>
          <%=link_to "עריכת טיפול זה", edit_visit_path(@visit),remote: true, :class => "btn btn-primary btn-md btn-block"%>
        </div>
        <div class="col-xs-4" id="open_close_button">
          <%= render 'status' %>
          </div>
                <div class="col-xs-4">
             <br>
          <%=link_to "הצג כל הביקורים ברכב זה", car_visits_path(@visit), remote: true, :class => "btn btn-primary btn-md" %>
          </div>
        <div class="col-xs-12">
          <%=label_tag "הערות לטיפול" %>
          <%=text_area_tag :notes ,f.notes, disabled: true, :class => 'form-control', :rows => 7%>
        </div>

      </div>
    </div>
  </div>
</div> <!-- /container -->

<div class="container" id="visit_items">
  <div class="panel panel-default" >
      <div class="panel-heading">פרטי טיפול ברכב <%=@owner.car_number%> מיום : <%=@visit.created_at.strftime("%d/%m/%Y")%>
      </div>
    <div class="panel-body"> פירוט טיפולים

 

        
    <table class="table table-hover">
        <%=render 'table_of_shit'%>
    </table>  

   </div>

</div>
</div>

app/views/visits/_table_of_shit.html.erb
     <thead>
        <tr>
          <th> X </th>
          <th>סוג טיפול</th>
          <th>תיאור</th>
          <th>מחיר</th>
        </tr>
      </thead>
      <tbody id="table-of-items">

              <% 
          total = 0
          unless @items.empty?
           @items.each do |i| 
          total += i.price.to_i
        %>
      <tr id="item-row<%=i.id%>">
        <td> <%= link_to "X", {:controller => "visits", :action => 'destroy_item_visit', :item_id => i.id },remote: true, data: { confirm: 'Are you sure you want to delete this alert?' }, :method => :delete %>
 </td>
        <td><%=i.title%></td>
        <td><%=i.description%></td>
        <td><%=i.price%></td>
      </tr>
<% end %>

      <tr>
             <td></td>
              <td>סכ"ה</td>

        <td><%=total%></td>

      </tr>
<% else %>
<tr>
  <td>
    אין טיפולים לרכב זה
  </td>
</tr>
<% end %>

    </tbody>

app/views/visits/edit.js.erb
$("#container_index").html("<%= j (render 'edit') %>")

app/views/visits/find_car.js.erb
$("#container_index").html("<%= j (render 'find_car') %>")

app/views/visits/index.html.erb
        <%= render "index" %>

app/views/visits/index.js.erb
$("#container_index").html("<%= j (render 'index') %>")

app/views/visits/new.js.erb
$("#container_index").html("<%= j (render 'new') %>");

$(document).ready(function(){

    $("#clicked_add").click(function(){
    	$("#clicked_add").hide();
        $("#new_owner_div").show();
        $("#not_found_label").hide();
        alert('sss');
      
    }



    );



});


  
    // Setup form validation on the #register-form element
  

app/views/visits/status.js.erb
$("#open_close_button").html("<%= j (render 'status') %>")
$("#fuckit").html("FUCK THE FUCKEN FUCKERS")

app/views/visits/update.js.erb
$("#container_index").html("<%= j (render 'show') %>")